In [53]:
import numpy as np
import numpy.ma as ma

In [54]:
lats = np.asarray([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
lons = np.asarray([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])
data = np.asarray([111, 112, 113, 114, 115, 116, 116, 118, 119, 120])

In [55]:
lats_mask = ma.masked_where(np.logical_or(lats <= 2, lats >= 9), lats)
lats_mask.mask

array([ True,  True, False, False, False, False, False, False,  True,
        True])

In [56]:
lons_mask = ma.masked_where(np.logical_or(lons <= 54, lons >= 57), lons)
lons_mask.mask

array([ True,  True,  True,  True, False, False,  True,  True,  True,
        True])

In [58]:
filtered_data = np.where(((lats == lats_mask) & (lons == lons_mask)), data, 9999)

In [59]:
print(filtered_data)

[9999 9999 9999 9999  115  116 9999 9999 9999 9999]
